site_name: Fast Dash
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.snippets

theme:
  name: material
  logo: assets/favicon.ico
  favicon: assets/favicon.ico
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  features:
    - navigation.tracking

repo_name: fast_dash
repo_url: https://github.com/dkedar7/fast_dash

nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - User guide:
    - Under the hood: User guide/build.md
    - Fast Components: User guide/components.md
    - Common patterns: User guide/patterns.md
    - Deployment: User guide/deployment.md
  - Examples:
    - 1. Simple text to text: Examples/simple_text_to_text.md
    - 2. English to French translation: Examples/english_to_french_translation.md
    - 3. Translate from English to multiple languages: Examples/english_to_multiple_translation.md
    - 4. Neural style transfer: Examples/neural_style_transfer.md
  - Modules: api.md
  - Contributing: contributing.md
  - Authors: authors.md
  - History: history.md

plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      handlers:
          python:
              setup_commands:
                  - import sys
                  - sys.path.append('../')
              selection:
                  new_path_syntax: true

extra_css:
  - css/termynal.css
  - css/custom.css
extra_javascript:
  - js/termynal.js
  - js/custom.js